spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://localhost:3306/course?useSSL=false&serverTimezone=UTC&characterEncoding
      =utf8&autoReconnect=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.hjc.server.mapper: trace


